// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oegheuxfmotihccxxszj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lZ2hldXhmbW90aWhjY3h4c3pqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzI5ODYsImV4cCI6MjA1NzgwODk4Nn0.XPFZ-mtMggYK2lsynZ0errzJzyFG0R_g6DXTU1MAo5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);